@echo off
setlocal EnableExtensions

set "ROOT=%~dp0"
set "COMPILER=D:\ARQUIVOS IMPORTANTES\REPOSITORIOS\CS 1.6\Compiler\amxxpc.exe"
set "COMPILER_INCLUDE=D:\ARQUIVOS IMPORTANTES\REPOSITORIOS\CS 1.6\Compiler\include"
set "PROJECT_INCLUDE=%ROOT%include"
set "PACKAGE_ROOT=%ROOT%build\cstrike"
set "PLUGIN_DIR=%PACKAGE_ROOT%\addons\amxmodx\plugins\rezombie"
set "CONFIG_DIR=%PACKAGE_ROOT%\addons\amxmodx\configs"
set "PLUGIN_CONFIG=%CONFIG_DIR%\plugins-rezombie.ini"
set "DEV_PLUGIN_CONFIG=%CONFIG_DIR%\plugins-rezombie-dev.ini"
set "RESOURCES_DIR=%ROOT%resources"

if not exist "%COMPILER%" (
	echo ERROR: AMX Mod X compiler was not found: %COMPILER%
	exit /b 1
)

if not exist "%PROJECT_INCLUDE%\rezombie.inc" (
	echo ERROR: Project includes were not found: %PROJECT_INCLUDE%
	exit /b 1
)

if exist "%PACKAGE_ROOT%" (
	rmdir /s /q "%PACKAGE_ROOT%"
	if errorlevel 1 (
		echo ERROR: Failed to clean build package: %PACKAGE_ROOT%
		exit /b 1
	)
)

mkdir "%PLUGIN_DIR%" >nul 2>nul
if errorlevel 1 (
	echo ERROR: Failed to create plugin directory: %PLUGIN_DIR%
	exit /b 1
)

mkdir "%CONFIG_DIR%" >nul 2>nul
if errorlevel 1 (
	echo ERROR: Failed to create config directory: %CONFIG_DIR%
	exit /b 1
)

echo Compiling source\api\ApiProps.sma
"%COMPILER%" "%ROOT%source\api\ApiProps.sma" "-i%PROJECT_INCLUDE%" "-i%COMPILER_INCLUDE%" "-o%PLUGIN_DIR%\ApiProps.amxx"
if errorlevel 1 exit /b 1

echo Compiling source\api\ApiModels.sma
"%COMPILER%" "%ROOT%source\api\ApiModels.sma" "-i%PROJECT_INCLUDE%" "-i%COMPILER_INCLUDE%" "-o%PLUGIN_DIR%\ApiModels.amxx"
if errorlevel 1 exit /b 1

echo Compiling source\api\ApiClasses.sma
"%COMPILER%" "%ROOT%source\api\ApiClasses.sma" "-i%PROJECT_INCLUDE%" "-i%COMPILER_INCLUDE%" "-o%PLUGIN_DIR%\ApiClasses.amxx"
if errorlevel 1 exit /b 1

echo Compiling source\api\ApiSubclasses.sma
"%COMPILER%" "%ROOT%source\api\ApiSubclasses.sma" "-i%PROJECT_INCLUDE%" "-i%COMPILER_INCLUDE%" "-o%PLUGIN_DIR%\ApiSubclasses.amxx"
if errorlevel 1 exit /b 1

echo Compiling source\api\ApiModes.sma
"%COMPILER%" "%ROOT%source\api\ApiModes.sma" "-i%PROJECT_INCLUDE%" "-i%COMPILER_INCLUDE%" "-o%PLUGIN_DIR%\ApiModes.amxx"
if errorlevel 1 exit /b 1

echo Compiling source\api\ApiPlayers.sma
"%COMPILER%" "%ROOT%source\api\ApiPlayers.sma" "-i%PROJECT_INCLUDE%" "-i%COMPILER_INCLUDE%" "-o%PLUGIN_DIR%\ApiPlayers.amxx"
if errorlevel 1 exit /b 1

echo Compiling source\classes\Human.sma
"%COMPILER%" "%ROOT%source\classes\Human.sma" "-i%PROJECT_INCLUDE%" "-i%COMPILER_INCLUDE%" "-o%PLUGIN_DIR%\Human.amxx"
if errorlevel 1 exit /b 1

echo Compiling source\classes\Zombie.sma
"%COMPILER%" "%ROOT%source\classes\Zombie.sma" "-i%PROJECT_INCLUDE%" "-i%COMPILER_INCLUDE%" "-o%PLUGIN_DIR%\Zombie.amxx"
if errorlevel 1 exit /b 1

echo Compiling source\classes\Fleshpound.sma
"%COMPILER%" "%ROOT%source\classes\Fleshpound.sma" "-i%PROJECT_INCLUDE%" "-i%COMPILER_INCLUDE%" "-o%PLUGIN_DIR%\Fleshpound.amxx"
if errorlevel 1 exit /b 1

echo Compiling source\gamemodes\Infection.sma
"%COMPILER%" "%ROOT%source\gamemodes\Infection.sma" "-i%PROJECT_INCLUDE%" "-i%COMPILER_INCLUDE%" "-o%PLUGIN_DIR%\Infection.amxx"
if errorlevel 1 exit /b 1

echo Compiling source\core\GameRules.sma
"%COMPILER%" "%ROOT%source\core\GameRules.sma" "-i%PROJECT_INCLUDE%" "-i%COMPILER_INCLUDE%" "-o%PLUGIN_DIR%\GameRules.amxx"
if errorlevel 1 exit /b 1

echo Compiling source\dev\DevRuntime.sma
"%COMPILER%" "%ROOT%source\dev\DevRuntime.sma" "-i%PROJECT_INCLUDE%" "-i%COMPILER_INCLUDE%" "-o%PLUGIN_DIR%\DevRuntime.amxx"
if errorlevel 1 exit /b 1

> "%PLUGIN_CONFIG%" echo ; ReZombie Plugins
>> "%PLUGIN_CONFIG%" echo ; Generated by build.bat.
>> "%PLUGIN_CONFIG%" echo.
>> "%PLUGIN_CONFIG%" echo ; Core APIs
>> "%PLUGIN_CONFIG%" echo rezombie/ApiProps.amxx
>> "%PLUGIN_CONFIG%" echo rezombie/ApiModels.amxx
>> "%PLUGIN_CONFIG%" echo rezombie/ApiClasses.amxx
>> "%PLUGIN_CONFIG%" echo rezombie/ApiSubclasses.amxx
>> "%PLUGIN_CONFIG%" echo rezombie/ApiModes.amxx
>> "%PLUGIN_CONFIG%" echo rezombie/ApiPlayers.amxx
>> "%PLUGIN_CONFIG%" echo.
>> "%PLUGIN_CONFIG%" echo ; Classes
>> "%PLUGIN_CONFIG%" echo rezombie/Human.amxx
>> "%PLUGIN_CONFIG%" echo rezombie/Zombie.amxx
>> "%PLUGIN_CONFIG%" echo rezombie/Fleshpound.amxx
>> "%PLUGIN_CONFIG%" echo.
>> "%PLUGIN_CONFIG%" echo ; Game Modes
>> "%PLUGIN_CONFIG%" echo rezombie/Infection.amxx
>> "%PLUGIN_CONFIG%" echo.
>> "%PLUGIN_CONFIG%" echo ; Game Rules
>> "%PLUGIN_CONFIG%" echo rezombie/GameRules.amxx
if errorlevel 1 (
	echo ERROR: Failed to write plugin config: %PLUGIN_CONFIG%
	exit /b 1
)

> "%DEV_PLUGIN_CONFIG%" echo ; ReZombie Dev Plugins
>> "%DEV_PLUGIN_CONFIG%" echo ; Generated by build.bat.
>> "%DEV_PLUGIN_CONFIG%" echo ; Load only on local validation servers.
>> "%DEV_PLUGIN_CONFIG%" echo.
>> "%DEV_PLUGIN_CONFIG%" echo rezombie/DevRuntime.amxx
if errorlevel 1 (
	echo ERROR: Failed to write dev plugin config: %DEV_PLUGIN_CONFIG%
	exit /b 1
)

if exist "%RESOURCES_DIR%" (
	xcopy "%RESOURCES_DIR%\*" "%PACKAGE_ROOT%\" /E /I /Y >nul
	if errorlevel 1 (
		echo ERROR: Failed to copy resources from: %RESOURCES_DIR%
		exit /b 1
	)
)

echo Build completed: %PACKAGE_ROOT%
exit /b 0
