@echo off
setlocal EnableExtensions EnableDelayedExpansion

set "ROOT=%~dp0"
for %%I in ("%ROOT%..\..") do set "CS_ROOT=%%~fI"

set "COMPILER=%CS_ROOT%\Compiler\amxxpc.exe"
set "COMPILER_INCLUDE=%CS_ROOT%\Compiler\include"
set "PROJECT_INCLUDE=%ROOT%include"
set "MANIFEST=%ROOT%plugins.manifest"
set "BUILD_ROOT=%ROOT%build"
set "BUILD_LOG=%BUILD_ROOT%\build.log"
set "COMPILER_OUTPUT=%BUILD_ROOT%\compiler-output.tmp"
set "PACKAGE_ROOT=%BUILD_ROOT%\cstrike"
set "PLUGIN_ROOT=%PACKAGE_ROOT%\addons\amxmodx\plugins\rezombie"
set "CONFIG_DIR=%PACKAGE_ROOT%\addons\amxmodx\configs"
set "PLUGIN_CONFIG=%CONFIG_DIR%\plugins-rezombie.ini"
set "DEV_PLUGIN_CONFIG=%CONFIG_DIR%\plugins-rezombie-dev.ini"
set "RESOURCES_DIR=%ROOT%resources"
set "FAILED_SOURCE="
set "FAILED_OUTPUT="
set "FAILED_ERRORLEVEL="

if not exist "%BUILD_ROOT%\" mkdir "%BUILD_ROOT%" >nul 2>nul
if errorlevel 1 (
	echo ERROR: Failed to create build directory: %BUILD_ROOT%
	goto :BuildFailed
)

> "%BUILD_LOG%" echo ReZombie build log
>> "%BUILD_LOG%" echo Started: %DATE% %TIME%
>> "%BUILD_LOG%" echo Root: %ROOT%
>> "%BUILD_LOG%" echo.

if not exist "%COMPILER%" (
	echo ERROR: AMX Mod X compiler was not found: %COMPILER%
	goto :BuildFailed
)

if not exist "%PROJECT_INCLUDE%\rezombie.inc" (
	echo ERROR: Project includes were not found: %PROJECT_INCLUDE%
	goto :BuildFailed
)

if not exist "%MANIFEST%" (
	echo ERROR: Plugin manifest was not found: %MANIFEST%
	goto :BuildFailed
)

if exist "%PACKAGE_ROOT%" (
	rmdir /s /q "%PACKAGE_ROOT%"
	if errorlevel 1 (
		echo ERROR: Failed to clean build package: %PACKAGE_ROOT%
		goto :BuildFailed
	)
)

call :EnsureDirectory "%PLUGIN_ROOT%"
if errorlevel 1 goto :BuildFailed

call :EnsureDirectory "%CONFIG_DIR%"
if errorlevel 1 goto :BuildFailed

> "%PLUGIN_CONFIG%" echo ; ReZombie Plugins
>> "%PLUGIN_CONFIG%" echo ; Generated by build.bat from plugins.manifest.
>> "%PLUGIN_CONFIG%" echo.

> "%DEV_PLUGIN_CONFIG%" echo ; ReZombie Dev Plugins
>> "%DEV_PLUGIN_CONFIG%" echo ; Generated by build.bat from plugins.manifest.
>> "%DEV_PLUGIN_CONFIG%" echo ; Load only on local validation servers.
>> "%DEV_PLUGIN_CONFIG%" echo.

for /f "usebackq tokens=1-4 delims=|" %%A in ("%MANIFEST%") do (
	call :CompilePlugin "%%~A" "%%~B" "%%~C" "%%~D"
	if errorlevel 1 goto :BuildFailed
)

if exist "%RESOURCES_DIR%" (
	xcopy "%RESOURCES_DIR%\*" "%PACKAGE_ROOT%\" /E /I /Y >nul
	if errorlevel 1 (
		echo ERROR: Failed to copy resources from: %RESOURCES_DIR%
		goto :BuildFailed
	)
)

echo Build completed: %PACKAGE_ROOT%
echo Build log: %BUILD_LOG%
exit /b 0

:CompilePlugin
setlocal
set "ENVIRONMENT=%~1"
set "CATEGORY=%~2"
set "SOURCE=%~3"
set "CONFIG_FLAGS=%~4"

if "%ENVIRONMENT%"=="" exit /b 0

call :ResolveCategoryDirectory "%CATEGORY%"
if errorlevel 1 exit /b 1

if not exist "%ROOT%%SOURCE%" (
	echo ERROR: Plugin source was not found: %ROOT%%SOURCE%
	exit /b 1
)

for %%I in ("%SOURCE%") do set "PLUGIN_NAME=%%~nI"
set "OUTPUT=%CATEGORY_DIR%\%PLUGIN_NAME%.amxx"
set "CONFIG_ENTRY=rezombie/%CATEGORY%/%PLUGIN_NAME%.amxx"

call :EnsureDirectory "%CATEGORY_DIR%"
if errorlevel 1 exit /b 1

echo Compiling %SOURCE%
>> "%BUILD_LOG%" echo === Compiling %SOURCE% ===
>> "%BUILD_LOG%" echo Output: %OUTPUT%
>> "%BUILD_LOG%" echo Command: "%COMPILER%" "%ROOT%%SOURCE%" "-i%PROJECT_INCLUDE%" "-i%COMPILER_INCLUDE%" "-o%OUTPUT%"
"%COMPILER%" "%ROOT%%SOURCE%" "-i%PROJECT_INCLUDE%" "-i%COMPILER_INCLUDE%" "-o%OUTPUT%" > "%COMPILER_OUTPUT%" 2>&1
set "COMPILER_STATUS=%ERRORLEVEL%"
type "%COMPILER_OUTPUT%"
type "%COMPILER_OUTPUT%" >> "%BUILD_LOG%"
>> "%BUILD_LOG%" echo.
del "%COMPILER_OUTPUT%" >nul 2>nul
if not "%COMPILER_STATUS%"=="0" (
	endlocal & set "FAILED_SOURCE=%SOURCE%" & set "FAILED_OUTPUT=%OUTPUT%" & set "FAILED_ERRORLEVEL=%COMPILER_STATUS%" & exit /b 1
)

if /i "%ENVIRONMENT%"=="main" (
	>> "%PLUGIN_CONFIG%" echo %CONFIG_ENTRY%
) else if /i "%ENVIRONMENT%"=="dev" (
	>> "%DEV_PLUGIN_CONFIG%" echo %CONFIG_ENTRY% %CONFIG_FLAGS%
) else (
	echo ERROR: Invalid plugin environment '%ENVIRONMENT%' in plugins.manifest.
	exit /b 1
)

endlocal
exit /b 0

:ResolveCategoryDirectory
set "CATEGORY_DIR="
if /i "%~1"=="api" set "CATEGORY_DIR=%PLUGIN_ROOT%\api"
if /i "%~1"=="classes" set "CATEGORY_DIR=%PLUGIN_ROOT%\classes"
if /i "%~1"=="core" set "CATEGORY_DIR=%PLUGIN_ROOT%\core"
if /i "%~1"=="dev" set "CATEGORY_DIR=%PLUGIN_ROOT%\dev"
if /i "%~1"=="gamemodes" set "CATEGORY_DIR=%PLUGIN_ROOT%\gamemodes"
if /i "%~1"=="hud" set "CATEGORY_DIR=%PLUGIN_ROOT%\hud"

if not defined CATEGORY_DIR (
	echo ERROR: Invalid plugin category '%~1' in plugins.manifest.
	exit /b 1
)

exit /b 0

:EnsureDirectory
if exist "%~1\" exit /b 0
mkdir "%~1" >nul 2>nul
if errorlevel 1 (
	echo ERROR: Failed to create directory: %~1
	exit /b 1
)
exit /b 0

:BuildFailed
echo.
echo Build failed. Review the error above.
if defined FAILED_SOURCE (
	echo.
	echo Failed source: %FAILED_SOURCE%
	if defined FAILED_OUTPUT echo Target output: %FAILED_OUTPUT%
	if defined FAILED_ERRORLEVEL echo Compiler exit code: %FAILED_ERRORLEVEL%
)
if exist "%BUILD_LOG%" (
	echo.
	echo Compiler diagnostics:
	findstr /I /C:": error " /C:"fatal error" "%BUILD_LOG%"
	if errorlevel 1 echo No compiler error lines were found in the log.
	echo.
	echo Full log: %BUILD_LOG%
)
if /i not "%BUILD_NO_PAUSE%"=="1" pause
exit /b 1
